name: reportree
channels:
  - etetoolkit
  - anaconda
  - bioconda
  - conda-forge
  - defaults
  - insapathogenomics
dependencies:
  - biopython=1.77
  - cgmlst-dists_genpat-it=0.4.0
  - ete3
  - grapetree=2.1
  - numba=0.55.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.1.3
  - python=3.8
  - scikit-learn
  - snp-sites=2.5.1
  - treecluster=1.0.3
  - zip
  - pytest