name: nextflow linting
# This workflow is triggered on pushes and PRs to the repository to ensure
# valid code is being contributed. 

on:
  push:
    branches:
      - dev
      - TEMPLATE
  pull_request:
  release:
    types: [published]

jobs:
  nextflow-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v3
        with:
          version: 26.04.3

      - name: Run Nextflow lint
        run: nextflow lint *

